### ISSUE TITLE
Spigot 1.15 support

### ISSUE THREAD

**Issue by SlimeDog** [Qveshn/LightAPI#10]
Spigot 1.15 (Jenkins 2513)
LightAPI 3.4.1

On server start-up:
```
[04:01:10] [Server thread/INFO]: [LightAPI] Enabling LightAPI v3.4.1
[04:01:10] [Server thread/ERROR]: [LightAPI] Could not find handler for this Bukkit Spigot implementation v1_15_R1 version.
[04:01:10] [Server thread/WARN]: ru.beykerykt.lightapi.server.exceptions.UnknownNMSVersionException: Could not find handler for this Bukkit Spigot implementation v1_15_R1 version.
[04:01:10] [Server thread/WARN]:        at ru.beykerykt.lightapi.server.ServerModManager.init(ServerModManager.java:62)
[04:01:10] [Server thread/WARN]:        at ru.beykerykt.lightapi.LightAPI.onEnable(LightAPI.java:195)
[04:01:10] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[04:01:10] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[04:01:10] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
[04:01:10] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462)
[04:01:10] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376)
[04:01:10] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:456)
[04:01:10] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:266)
[04:01:10] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:783)
[04:01:10] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[04:01:10] [Server thread/INFO]: [LightAPI] Disabling LightAPI v3.4.1
```

**Comment by Qveshn** [comment]
ок. time to update it for 1.15 😃

**Comment by Qveshn** [comment]
I have made 1.15 support and tested it. All worrks. Release will be in 1-2 days  
ATM I am thinking about auto-multi-platform support (Bukkit, Paper, Akarin, ... and so on)

**Comment by SlimeDog** [comment]
Thanks. Awaiting with bated breath. :)

**Comment by Qveshn** [comment]
Done

**Comment by SlimeDog** [comment]
Confirmed LightAPI 3.4.2 works great on Spigot 1.15.1, based on testing with ShinyItems 1.7.2
