### ISSUE TITLE
Error when loading LightAPI on 1.15.2 Paper

### ISSUE THREAD

**Issue by TUCAOEVER** [Qveshn/LightAPI#21]
```
[17:57:36] [Server thread/INFO]: [LightAPI] Enabling LightAPI v3.4.5
[17:57:36] [Server thread/INFO]: [LightAPI] Loading implementation for Paper server v1_15_R1.
[17:57:36] [Server thread/ERROR]: Error occurred while enabling LightAPI v3.4.5 (Is it up to date?)
java.lang.IllegalArgumentException: null
	at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleWithFixedDelay(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.Executors$DelegatedScheduledExecutorService.scheduleWithFixedDelay(Unknown Source) ~[?:1.8.0_261]
	at ru.beykerykt.lightapi.request.RequestSteamMachine.start(RequestSteamMachine.java:53) ~[?:?]
	at ru.beykerykt.lightapi.LightAPI.onEnable(LightAPI.java:243) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-389]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-389]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-389]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-389]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-389]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-389]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-389]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-389]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
[17:57:36] [Server thread/INFO]: [LightAPI] Disabling LightAPI v3.4.5
```

**Comment by Qveshn** [comment]
Hi
Please, post here contents or attach the file plugins/LightAPI/config.yml
I think I know what the problem 😃
