### ISSUE TITLE
[WARN] LightAPIFork on paper 1.17.1-233

### ISSUE THREAD

**Issue by fnrcum** [Qveshn/LightAPI#37]
Currently this warning pops up on paper 1.17.1-233
```
[17:45:03 WARN]: java.lang.ClassCastException: class ca.spottedleaf.starlight.light.StarLightInterface$2 cannot be cast to class net.minecraft.world.level.lighting.LightEngineBlock (ca.spottedleaf.starlight.light.StarLightInterface$2 and net.minecraft.world.level.lighting.LightEngineBlock are in unnamed module of loader 'app')
[17:45:03 WARN]:        at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.server.nms.craftbukkit.CraftBukkit_v1_17_R1$2.run(CraftBukkit_v1_17_R1.java:166)
[17:45:03 WARN]:        at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.server.nms.craftbukkit.CraftBukkit_v1_17_R1.executeSync(CraftBukkit_v1_17_R1.java:242)
[17:45:03 WARN]:        at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.server.nms.craftbukkit.CraftBukkit_v1_17_R1.recalculateLighting(CraftBukkit_v1_17_R1.java:159)
[17:45:03 WARN]:        at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.server.nms.craftbukkit.CraftBukkit_v1_17_R1.createLight(CraftBukkit_v1_17_R1.java:97)
[17:45:03 WARN]:        at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.LightAPI$1.run(LightAPI.java:320)
[17:45:03 WARN]:        at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.request.RequestSteamMachine.run(RequestSteamMachine.java:120)
[17:45:03 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[17:45:03 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[17:45:03 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[17:45:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[17:45:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[17:45:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by Qveshn** [comment]
Unfortunately the Staright engine does not support custom lights. Therefore, LightAPI is not compatible with the servers in which StarLight is implemented.

**Comment by EchocallingEarth** [comment]
> Unfortunately the Starlight engine does not support custom lights. Therefore, LightAPI is not compatible with the servers in which StarLight is implemented.

So in short this plugin is now useless has Paper appears to be using Starlight as well(this since they combined Tuinity). Which, means that any plugins like ItemsAdder, etc had the best start looking for something new. Including me as I was working on a plugin that would have relied on this. Hmmmm. That sucks.

**Comment by LOOHP** [comment]
It is unlikely that you can find alternatives, the whole light engine is rewritten, which probably means other light plugins will break as well.

**Comment by EchocallingEarth** [comment]
Ughhh, this means I hope a rewrite is underway. Heck, I'd pay for a plugin that fixed this especially now. Because let's be honest clearly StarLight is the new way.
