### ISSUE TITLE
[BUG] starlight.light.StarLightInterface

### ISSUE THREAD

**Issue by ghtg** [Qveshn/LightAPI#39]
[01:14:42 WARN]: java.lang.ClassCastException: class ca.spottedleaf.starlight.light.StarLightInterface$2 cannot be cast to class net.minecraft.world.level.lighting.LightEngineBlock (ca.spottedleaf.starlight.light.StarLightInterface$2 and net.minecraft.world.level.lighting.LightEngineBlock are in unnamed module of loader 'app')
[01:14:42 WARN]:        at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.server.nms.craftbukkit.CraftBukkit_v1_17_R1$2.run(CraftBukkit_v1_17_R1.java:166)
[01:14:42 WARN]:        at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.server.nms.craftbukkit.CraftBukkit_v1_17_R1.executeSync(CraftBukkit_v1_17_R1.java:242)
[01:14:42 WARN]:        at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.server.nms.craftbukkit.CraftBukkit_v1_17_R1.recalculateLighting(CraftBukkit_v1_17_R1.java:159)
[01:14:42 WARN]:        at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.server.nms.craftbukkit.CraftBukkit_v1_17_R1.createLight(CraftBukkit_v1_17_R1.java:97)
[01:14:42 WARN]:        at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.LightAPI$1.run(LightAPI.java:320)
[01:14:42 WARN]:        at LightAPI-fork-3.5.2.jar//ru.beykerykt.lightapi.request.RequestSteamMachine.run(RequestSteamMachine.java:120)
[01:14:42 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[01:14:42 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[01:14:42 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[01:14:42 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[01:14:42 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[01:14:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

server:1.17.1 papermc
client: opifine 1.17.1
lightapi: 3.5.2

**Comment by EchocallingEarth** [comment]
See issues 32 to 38. The Dev is aware. 

#32 #35 #37 #36 #38 #
