### ISSUE TITLE
Spigot 1.14 Support

### ISSUE THREAD

**Issue by LJack2k** [Qveshn/LightAPI#5]
Today I've been migrating my spigot 1.13 server to 1.14 and I came across this error. I hope you are still maintaining this plugin and hopefully its a easy fix. If you need more information let me know.

[15:55:15] [Server thread/INFO]: [LightAPI] Enabling LightAPI v3.2.9
[15:55:15] [Server thread/INFO]: [0;36;1m<LightAPI>: [0;37;1m[0;31;1mCould not find handler for this Bukkit [0;37;1mSpigot[0;31;1m implementation [0;37;1mv1_14_R1[0;31;1m version.[m
[15:55:15] [Server thread/WARN]: ru.beykerykt.lightapi.server.exceptions.UnknownNMSVersionException: Could not find handler for this Bukkit Spigot implementation v1_14_R1 version.
[15:55:15] [Server thread/WARN]: 	at ru.beykerykt.lightapi.server.ServerModManager.init(ServerModManager.java:62)
[15:55:15] [Server thread/WARN]: 	at ru.beykerykt.lightapi.LightAPI.onEnable(LightAPI.java:172)
[15:55:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[15:55:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[15:55:15] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416)
[15:55:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458)
[15:55:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372)
[15:55:15] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440)
[15:55:15] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258)
[15:55:15] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761)
[15:55:15] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:55:15] [Server thread/INFO]: [LightAPI] Disabling LightAPI v3.2.9

**Comment by SamB440** [comment]
Took a look at the code, unfortunately it seems a lot of NMS has changed. Hopefully Qveshn can work it out though...

**Comment by Sv443** [comment]
Yup, I have got the same issue. Here's my startup log:
```
[09:34:34] [Server thread/INFO]: [LightAPI] Enabling LightAPI v3.2.9
[09:34:34] [Server thread/INFO]: <LightAPI>: Could not find handler for this Bukkit Spigot implementation v1_14_R1 version.
[09:34:34] [Server thread/WARN]: ru.beykerykt.lightapi.server.exceptions.UnknownNMSVersionException: Could not find handler for this Bukkit Spigot implementation v1_14_R1 version.
[09:34:34] [Server thread/WARN]:        at ru.beykerykt.lightapi.server.ServerModManager.init(ServerModManager.java:62)
[09:34:34] [Server thread/WARN]:        at ru.beykerykt.lightapi.LightAPI.onEnable(LightAPI.java:172)
[09:34:34] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[09:34:34] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[09:34:34] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416)
[09:34:34] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458)
[09:34:34] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372)
[09:34:34] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440)
[09:34:34] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258)
[09:34:34] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:758)
[09:34:34] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[09:34:34] [Server thread/INFO]: [LightAPI] Disabling LightAPI v3.2.9
```

I'm using the latest Spigot 1.14 dev build and these plugins:

![grafik](https://user-images.githubusercontent.com/38158426/57398178-abbcf580-71ce-11e9-9ce9-fa96afdc6807.png)

**Comment by Qveshn** [comment]
LightAPI does not support 1.14 yet. I will look how to upgrade it

**Comment by Sv443** [comment]
I just noticed this is a fork.
Are you now maintaining LightAPI or should I move my issue to the original repo @Qveshn?

**Comment by Qveshn** [comment]
Now LightAPI fork supports 1.8-1.14
https://www.spigotmc.org/resources/lightapi-fork.48247/
=)

**Comment by Qveshn** [comment]
No reaction for a long time. Issue will be closed as fixed.

**Comment by Qveshn** [comment]
Issue is closed as fixed
