### ISSUE TITLE
Paper support

### ISSUE THREAD

**Issue by PsychoLynx** [Qveshn/LightAPI#6]
Hi!

I have been looking forward to using ShinyItems on my server again. Unfortunately, I am running a Paper based server, which LightAPI does not seem to support presently. A look into this would be highly appreciated!

Below is my server startup log regarding the new LightAPI

[08:57:38] [Server thread/INFO]: [LightAPI] Enabling LightAPI v3.3.0*
[08:57:38] [Server thread/INFO]: <LightAPI>: Could not find handler for this Bukkit Paper implementation v1_14_R1 version.
[08:57:38] [Server thread/WARN]: ru.beykerykt.lightapi.server.exceptions.UnknownNMSVersionException: Could not find handler for this Bukkit Paper implementation v1_14_R1 version.
[08:57:38] [Server thread/WARN]:     at ru.beykerykt.lightapi.server.ServerModManager.init(ServerModManager.java:61)
[08:57:38] [Server thread/WARN]:     at ru.beykerykt.lightapi.LightAPI.onEnable(LightAPI.java:180)
[08:57:38] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[08:57:38] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[08:57:38] [Server thread/WARN]:     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[08:57:38] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[08:57:38] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[08:57:38] [Server thread/WARN]:     at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
[08:57:38] [Server thread/WARN]:     at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282)
[08:57:38] [Server thread/WARN]:     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:869)
[08:57:38] [Server thread/WARN]:     at java.lang.Thread.run(Thread.java:748)
[08:57:38] [Server thread/INFO]: [LightAPI] Disabling LightAPI v3.3.0
[08:57:38] [Server thread/INFO]: [LightAPI] Enabling LightAPI v3.3.0*
[08:57:38] [Server thread/INFO]: <LightAPI>: Could not find handler for this Bukkit Paper implementation v1_14_R1 version.
[08:57:38] [Server thread/WARN]: ru.beykerykt.lightapi.server.exceptions.UnknownNMSVersionException: Could not find handler for this Bukkit Paper implementation v1_14_R1 version.
[08:57:38] [Server thread/WARN]:     at ru.beykerykt.lightapi.server.ServerModManager.init(ServerModManager.java:61)
[08:57:38] [Server thread/WARN]:     at ru.beykerykt.lightapi.LightAPI.onEnable(LightAPI.java:180)
[08:57:38] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[08:57:38] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[08:57:38] [Server thread/WARN]:     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[08:57:38] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[08:57:38] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[08:57:38] [Server thread/WARN]:     at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
[08:57:38] [Server thread/WARN]:     at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282)
[08:57:38] [Server thread/WARN]:     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:869)
[08:57:38] [Server thread/WARN]:     at java.lang.Thread.run(Thread.java:748)
[08:57:38] [Server thread/INFO]: [LightAPI] Disabling LightAPI v3.3.0

**Comment by Qveshn** [comment]
Here you are: https://www.spigotmc.org/resources/lightapi-fork.48247/update?update=289855
=)

**Comment by PsychoLynx** [comment]
Thank you kindly!

**Comment by PsychoLynx** [comment]
Seems to be working. Thank you again :)
